spring:
  application:
    name: service-cms #当前应用名 在动态配置和注册服务的时候使用
  datasource: #配置数据库连接信息
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_cms?serverTimezone=GMT%2B8
  jackson: #JSON格式化时间日期格式设置，当后端向前端传递json时间类型时，前端显示的数据格式
    time-zone: GMT+8 #东八区
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: #激活专有环境（应用：全局统一日志、nacos配置中心动态配置）
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  #将该服务注册到端口号为8848的nacos注册服务中心

    sentinel: #开启sentinel
      transport:
        port: 8081 #指定和sentinel控制台交流的端口号
        dashboard: localhost:8080 #指定控制台服务的地址
      eager: true #取消来加载（sentinel默认采用懒加载，只用应用被访问的时候才会加载到控制台）
      filter:
        url-patterns: /** #默认拦截路径

  redis:
    host: 192.168.230.128 #配置Redis
    port: 6379
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0

mybatis-plus: #配置mp的日志信息 查看sql语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/atguigu/guli/service/cms/mapper/xml/*xml
    #当在mapper接口中自定义方法时，要和mapper.xml中的sql语句一起动态创建接口的实现类对象 告诉mbp xml文件所在位置
server:
  port: 8140 #当前应用的端口号

#  tomcat:
#    max-threads: 2 #设置Tomcat的最大并发数 默认为200 一般不做更改

service-oss: # 调用的提供者的名称  可以在配置类中使用@Bean创建RandomRule对象放进容器中，此时就会采用自己设置的策略进行负载均衡
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #设置负载均衡策略为随机，默认为轮询

    MaxAutoRetries: 0 # 同一实例最大重试次数，不包括首次调用，默认0
    MaxAutoRetriesNextServer: 1 # 重试其他实例的最大重试次数，不包括首次所选的server，默认1

#    ConnectTimeout: 10000 #连接建立的超时时长，默认1秒
#    ReadTimeout: 10000 #处理请求的超时时间，默认为1秒

#logging: #配置日志等级
#  level:
#    com.atguigu.guli.service.edu.feign.OssFeignClient: debug #以什么级别监控哪个接口

feign:
  sentinel:
    enabled: true #开启openfeign对sentinel的支持
